### PR TITLE
SWIFT-239 use BSONType instead of libbson equivalent

### PR DESCRIPTION
**Pull request by kmahar**
Due to reasons we've yet to exactly determine, the driver will not build in Swift 4.2 in some cases due to an error about BSON_TYPE_CODE not being defined. This switches to using our own BSONType enum (which we should've been doing in the first place) and fixes the compilation errors in 4.2.

### CODE REVIEW

**Comment by kmahar** [comment]
That's my suspicion / hope :)

**Comment by mbroadst** [comment]
Is this the only place you are still using the `BSON_TYPE` enums?

**Comment by kmahar** [comment]
yep, no other BSON_TYPE_X usages
